# Settings

lang: ja
title: hanaのポートフォリオ
description: hanaのポートフォリオ
keywords: hana,hana-mignon,ポートフォリオ,はな,乙女
url: https://hana-mignon.github.io
ogimage: https://hana-mignon.github.io/image/avatar_hana_profile.png
icon: https://hana-mignon.github.io/image/avatar_hanaproficon.png
appleicon: https://hana-mignon.github.io/image/avatar_hanaproficon.png
exclude: ["README.md"]

# User
author: hana
twitter: hana-mignon
